### ISSUE TITLE
Check this

### ISSUE THREAD

**Issue by imrany** [ertush/kmhfl-upgrade-alpha-ui#155]
I tried opening the site url and got a 404 status.

**Comment by imrany** [comment]
this url.... http://kmhfl-upgrade-alpha-ui.vercel.app/

**Comment by ertush** [comment]
There was a merge that was done that caused an error in the build step, but that has been resolved. [https://kmhflv3.vercel.app/](https://kmhflv3.vercel.app/) is now working
